version: "3"
services:
  "zookeeper":
    image: wurstmeister/zookeeper ## 镜像
    ports:
      - "2181:2181" ## 对外暴露的端口号

  "kafka":
    image: wurstmeister/kafka ## 镜像
    volumes:
      - /etc/localtime:/etc/localtime ## 挂载位置（kafka镜像和宿主机器之间时间保持一直）
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.72.128 ## 修改:宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 ## 卡夫卡运行是基于zookeeper的
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: 120
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DELETE_RETENTION_MS: 1000

  "kafka-manager":
    image: sheepkiller/kafka-manager ## 镜像：开源的web管理kafka集群的界面
    environment:
      ZK_HOSTS: 192.168.72.128 ## 修改:宿主机IP
    ports:
      - "9000:9000" ## 暴露端口

  "redis":
    image: redis
    ports:
      - "6379:6379"

  "mysql":
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
